name: "Build"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - 'main'
    paths:
      - "build.sh"
      - ".github/workflows/*.yml"
      - "wslconf/*"

permissions:
  contents: write  

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    outputs:
      RELEASE: ${{ steps.start_build.outputs.RELEASE }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: start_build
        run: |
          bash build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: x86_64
          path: ./*.wsl

  build-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: start_build
        run: |
          bash build.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: aarch64
          path: ./*.wsl

  release:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-aarch64]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8

      - name: Release stable
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: latest
          files: |
            aarch64/void-*.wsl
            x86_64/void-*.wsl
          preserve_order: true
          make_latest: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}