name: Build Zip CI

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - 'src_x64_glibc/**'
      - 'src_arm64_glibc/**'
      - 'src_x64_musl/**'
      - 'src_arm64_musl/**'
  pull_request: 
    branches: [ 'main' ]
    paths:
      - 'src_x64_glibc/**'
      - 'src_arm64_glibc/**'
      - 'src_x64_musl/**'
      - 'src_arm64_musl/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install dependencies for build (Apt)
      shell: bash
      run: |
        sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
        sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libarchive-tools curl jq tree xz-utils

    - name: Build Zip glibc x64
      shell: bash
      env:
        ARCH: 'x64_glibc'
        OUT_ZIP: 'void-glibc.zip'
      run: |
        make -e
        sha256sum void-glibc.zip | tee void-glibc.zip.sha256
        ls -la

    - name: Build Zip glibc ARM64
      shell: bash
      env:
        ARCH: 'arm64_glibc'
        OUT_ZIP: 'void-glibc_arm64.zip'
      run: |
        make -e
        sha256sum void-glibc_arm64.zip | tee void-glibc_arm64.zip.sha256
        ls -la

    - name: Build Zip musl x64
      shell: bash
      env:
        ARCH: 'x64_musl'
        OUT_ZIP: 'void-musl.zip'
      run: |
        make -e
        sha256sum void-musl.zip | tee void-musl.zip.sha256
        ls -la

    - name: Build Zip musl ARM64
      shell: bash
      env:
        ARCH: 'arm64_musl'
        OUT_ZIP: 'void-musl_arm64.zip'
      run: |
        make -e
        sha256sum void-musl_arm64.zip | tee void-musl_arm64.zip.sha256
        ls -la

    - name: Upload a Build Artifact x64 glibc
      uses: actions/upload-artifact@main
      with:
        name: void-glibc.zip
        path: ./void-glibc.zip
    - name: Upload SHA256 Checksum x64 glibc
      uses: actions/upload-artifact@main
      with:
        name: void-glibc.zip.sha256
        path: ./void-glibc.zip.sha256
    - name: Upload a Build Artifact ARM64 glibc
      uses: actions/upload-artifact@main
      with:
        name: void-glibc_arm64.zip
        path: ./void-glibc_arm64.zip
    - name: Upload SHA256 Checksum ARM64 glibc
      uses: actions/upload-artifact@main
      with:
        name: void-glibc_arm64.zip.sha256
        path: ./void-glibc_arm64.zip.sha256    

    - name: Upload a Build Artifact x64 musl
      uses: actions/upload-artifact@main
      with:
        name: void-musl.zip
        path: ./void-musl.zip
    - name: Upload SHA256 Checksum x64 musl
      uses: actions/upload-artifact@main
      with:
        name: void-musl.zip.sha256
        path: ./void-musl.zip.sha256
    - name: Upload a Build Artifact ARM64 musl
      uses: actions/upload-artifact@main
      with:
        name: void-musl_arm64.zip
        path: ./void-musl_arm64.zip
    - name: Upload SHA256 Checksum ARM64 musl
      uses: actions/upload-artifact@main
      with:
        name: void-musl_arm64.zip.sha256
        path: ./void-musl_arm64.zip.sha256